/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface EmblaDatePicker {
    }
}
declare global {
    interface HTMLEmblaDatePickerElement extends Components.EmblaDatePicker, HTMLStencilElement {
    }
    var HTMLEmblaDatePickerElement: {
        prototype: HTMLEmblaDatePickerElement;
        new (): HTMLEmblaDatePickerElement;
    };
    interface HTMLElementTagNameMap {
        "embla-date-picker": HTMLEmblaDatePickerElement;
    }
}
declare namespace LocalJSX {
    interface EmblaDatePicker {
    }
    interface IntrinsicElements {
        "embla-date-picker": EmblaDatePicker;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "embla-date-picker": LocalJSX.EmblaDatePicker & JSXBase.HTMLAttributes<HTMLEmblaDatePickerElement>;
        }
    }
}
