/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface EmblaRouter {
    }
}
declare global {
    interface HTMLEmblaRouterElement extends Components.EmblaRouter, HTMLStencilElement {
    }
    var HTMLEmblaRouterElement: {
        prototype: HTMLEmblaRouterElement;
        new (): HTMLEmblaRouterElement;
    };
    interface HTMLElementTagNameMap {
        "embla-router": HTMLEmblaRouterElement;
    }
}
declare namespace LocalJSX {
    interface EmblaRouter {
    }
    interface IntrinsicElements {
        "embla-router": EmblaRouter;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "embla-router": LocalJSX.EmblaRouter & JSXBase.HTMLAttributes<HTMLEmblaRouterElement>;
        }
    }
}
