// Polyfill
import "@abytegray/embla-core/dist/polyfill.js";
// Import the whole library
import "@abytegray/embla-core";
// CSS
import "@abytegray/embla-core/dist/embla.css";
// Assets
import "./resources/android-chrome-192x192.png";
import "./resources/android-chrome-512x512.png";
import "./resources/apple-touch-icon.png";
import "./resources/browserconfig.xml";
import "./resources/favicon-16x16.png";
import "./resources/favicon-32x32.png";
import "./resources/favicon.ico";
import "./resources/mstile-70x70.png";
import "./resources/mstile-144x144.png";
import "./resources/mstile-150x150.png";
import "./resources/mstile-310x150.png";
import "./resources/mstile-310x310.png";
import "./resources/safari-pinned-tab.svg";
import "./resources/site.webmanifest";
